"""Generic migration script for Alembic.

Revision ID: 003d2a99a257
Revises: 0001_initial
Create Date: 2026-08-08 08:23:04.863668
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003d2a99a257'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('model_file', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'READY', 'ARCHIVED', 'FAILED', name='modelstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('attack_type', sa.String(length=128), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('prediction', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_detection_id'), 'predictions', ['detection_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.drop_table('analysis_results')
    op.drop_table('trained_models')
    op.drop_index(op.f('ix_threat_intelligence_indicator'), table_name='threat_intelligence_cache')
    op.drop_index(op.f('ix_threat_intelligence_provider'), table_name='threat_intelligence_cache')
    op.drop_table('threat_intelligence_cache')
    op.add_column('attacks', sa.Column('type', sa.String(length=128), nullable=False))
    op.add_column('attacks', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('attacks', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('attacks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('attacks', 'severity',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('attacks', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='attackstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.create_index(op.f('ix_attacks_severity'), 'attacks', ['severity'], unique=False)
    op.create_index(op.f('ix_attacks_timestamp'), 'attacks', ['timestamp'], unique=False)
    op.create_index(op.f('ix_attacks_type'), 'attacks', ['type'], unique=False)
    op.drop_constraint(None, 'attacks', type_='foreignkey')
    op.create_foreign_key(None, 'attacks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('attacks', 'created_at')
    op.drop_column('attacks', 'deleted_at')
    op.drop_column('attacks', 'attack_type')
    op.drop_column('attacks', 'updated_at')
    op.drop_column('attacks', 'user_id')
    op.drop_column('attacks', 'is_deleted')
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'created_at')
    op.add_column('incidents', sa.Column('attack_id', sa.UUID(), nullable=False))
    op.add_column('incidents', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incidentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))
    op.alter_column('incidents', 'priority',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('incidents', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_unique_constraint(None, 'incidents', ['attack_id'])
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'attacks', ['attack_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'incidents', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('incidents', 'analysis_result_id')
    op.drop_column('incidents', 'closed_at')
    op.drop_column('incidents', 'assigned_user_id')
    op.drop_column('incidents', 'opened_at')
    op.add_column('reports', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('reports', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'incident_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('reports', 'file_path')
    op.drop_column('reports', 'report_type')
    op.drop_column('reports', 'generated_by')
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('reports', sa.Column('generated_by', sa.NUMERIC(), nullable=True))
    op.add_column('reports', sa.Column('report_type', sa.VARCHAR(length=128), nullable=False))
    op.add_column('reports', sa.Column('file_path', sa.VARCHAR(length=512), nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['generated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'incident_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('reports', 'deleted_at')
    op.drop_column('reports', 'is_deleted')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'created_by')
    op.drop_column('reports', 'recommendations')
    op.drop_column('reports', 'summary')
    op.drop_column('reports', 'version')
    op.add_column('incidents', sa.Column('opened_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('incidents', sa.Column('assigned_user_id', sa.NUMERIC(), nullable=True))
    op.add_column('incidents', sa.Column('closed_at', sa.DATETIME(), nullable=True))
    op.add_column('incidents', sa.Column('analysis_result_id', sa.NUMERIC(), nullable=False))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'analysis_results', ['analysis_result_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'incidents', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'incidents', type_='unique')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.alter_column('incidents', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('incidents', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incidentstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))
    op.drop_column('incidents', 'assigned_to')
    op.drop_column('incidents', 'attack_id')
    op.add_column('audit_logs', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('audit_logs', sa.Column('status', sa.VARCHAR(length=32), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.NUMERIC(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'timestamp')
    op.add_column('attacks', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False))
    op.add_column('attacks', sa.Column('user_id', sa.NUMERIC(), nullable=False))
    op.add_column('attacks', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('attacks', sa.Column('attack_type', sa.VARCHAR(length=128), nullable=False))
    op.add_column('attacks', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.add_column('attacks', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.drop_constraint(None, 'attacks', type_='foreignkey')
    op.create_foreign_key(None, 'attacks', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_attacks_type'), table_name='attacks')
    op.drop_index(op.f('ix_attacks_timestamp'), table_name='attacks')
    op.drop_index(op.f('ix_attacks_severity'), table_name='attacks')
    op.alter_column('attacks', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='attackstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('attacks', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('attacks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('attacks', 'timestamp')
    op.drop_column('attacks', 'created_by')
    op.drop_column('attacks', 'type')
    op.create_table('threat_intelligence_cache',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('indicator', sa.VARCHAR(length=256), nullable=False),
    sa.Column('indicator_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=128), nullable=False),
    sa.Column('reputation_score', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('last_checked', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('raw_response', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_provider'), 'threat_intelligence_cache', ['provider'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_indicator'), 'threat_intelligence_cache', ['indicator'], unique=False)
    op.create_table('trained_models',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dataset', sa.VARCHAR(length=256), nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), nullable=False),
    sa.Column('accuracy', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('precision', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('recall', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('f1_score', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('trained_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('attack_id', sa.NUMERIC(), nullable=False),
    sa.Column('model_id', sa.NUMERIC(), nullable=False),
    sa.Column('prediction', sa.VARCHAR(length=256), nullable=False),
    sa.Column('confidence', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=32), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('recommendation', sa.TEXT(), nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_detection_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('detections')
    op.drop_table('models')
    op.drop_table('datasets')
    # ### end Alembic commands ###
